#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chmod +x $install_dir/warpgate

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
#ynh_script_progression "Adding $app's configuration files..."

#ynh_config_add --template="warpgate.yaml" --destination="$install_dir/warpgate.yaml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL WARPGATE
#=================================================
ynh_script_progression "Installing the app..."

pushd "$install_dir"
 	ynh_hide_warnings ./warpgate --config=$install_dir/warpgate.yaml unattended-setup --data-path="$data_dir" --http-port=$port --admin-password=$password #--mysql-port="3306" --database-url="mysql://$db_user:$db_pwd@127.0.0.1:3306/$db_name" --external-host
popd

chown -R $app: $install_dir
chown -R $app: $data_dir

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
